### ISSUE TITLE
message in Curator.py?

### ISSUE THREAD

**Issue by ilumsden** [danse-inelastic/pyre#10]
In Curator.py (pyre/python/pyre/inventory/odb/Curator.py), on line 78, there is the following code:
```
except TypeError(message)
```
What is `message` here? It is not used in the code that follows this statement, so is it even needed?

**Comment by yxqd** [comment]
At
https://github.com/danse-inelastic/pyre/blob/025372eb923f8a433f3785f9f8d68de51896f6ce/python/pyre/inventory/odb/Curator.py#L76

the code should be changed to 

`except TypeError as message:`

Please also refer to https://docs.python.org/3.3/howto/pyporting.html#capturing-the-currently-raised-exception
