### ISSUE TITLE
options.copyrightline in Stationery.py?

### ISSUE THREAD

**Issue by ilumsden** [danse-inelastic/pyre#11]
In Stationery.py (pyre/python/pyre/weaver/components/Stationery.py), on line 58, there is the following code:
```
... options.copyrightline % copyright ...
```
Is `options.copyrightline` a string? In other words, should the `% copyright` part of the above code be replaced with `.format(copyright)`?

**Comment by yxqd** [comment]
Yes `% copyright` should be replaced with `.format(...)`. And at https://github.com/danse-inelastic/pyre/blob/025372eb923f8a433f3785f9f8d68de51896f6ce/python/pyre/weaver/Weaver.py#L38 the default value should be changed from `"(C) %s  All Rights Reserved"` to `"(C) {}  All Rights Reserved"`

Please also fix the similar problem wtih https://github.com/danse-inelastic/pyre/blob/025372eb923f8a433f3785f9f8d68de51896f6ce/python/pyre/weaver/Weaver.py#L41 and https://github.com/danse-inelastic/pyre/blob/master/python/pyre/weaver/components/Mill.py#L95
