### ISSUE TITLE
Questions about division for Python 3 Compatibility.

### ISSUE THREAD

**Issue by ilumsden** [danse-inelastic/pyre#12]
In unit.py (pyre/python/pyre/unit/units.py) and Stationery.py (pyre/python/pyre/weaver/components/Stationery.py), there are several cases where I'm not sure whether the results of division are floats or ints. Since Python 3 has explicit operators for float division and floor division, I need to know whether the division returns a float or an int.

In unit.py, the cases of unspecific division are on lines __60, 62, 107__.

In Stationery.py, the case of unspecific division is on line __66__.

**Comment by yxqd** [comment]
* unit: these are floating point numbers for physical quantities. 
* Stationery: integer division (lengths)
