### ISSUE TITLE
Backwards Compatibility Break while Converting to Python 3 Support

### ISSUE THREAD

**Issue by ilumsden** [danse-inelastic/pyre#4]
In the Facility.py file (/pyre/python/pyre/inventory/Facility.py), on line 43, there is the following code:
```
if isinstance(component, basestring):
```
The problem is that `basestring` is no longer defined in Python 3. This is because, in Python 3, all strings are Unicode and the only other string type is the new `byte` type for representing data, which is different enough for Unicode strings that it was unreasonable for them to implement a new `basestring` class (their explanation, not mine).

I could just replace `basestring` with `str`, but this would break backwards compatibility. It may also be possible to import `unicode_literals` from `__future__`, which is supposed to add the Unicode-only string functionality to Python 2.6/2.7. However, I can't tell if that would just cast everything or provide access to the Python 3 version of the `str` type (and keyword). If it just does casting, this would not work, because the `Unicode` type doesn't exist in Python 3 (replaced with its version of `str`).

Any suggestions?

**Comment by yxqd** [comment]
Would it be OK that you test the version of python, and depending on the version of python, select an appropriate type? Sth like

```
PY_VER_MAJOR = ...

if PY_VER_MAJOR == 2:
  strtype = basestring
else:
  strtype = str
...
if isinstance(component, strtype):
  ...
```

**Comment by ilumsden** [comment]
That would probably work. I'll check.

**Comment by ilumsden** [comment]
Is it alright if I limit the Python 2 versions here to 2.7. There are other things in the code that will break backwards compatibility beyond Python 2.7.

**Comment by ilumsden** [comment]
I tested this with it checking for Python 2.7 or Python 3, and it worked. As of now, it's going to explicitly check that you either have Python 2.7 or Python 3. If you would rather me make it so that it checks for any version of Python 2 or 3, just let me know.

**Comment by yxqd** [comment]
That sounds good. Thanks!
