### ISSUE TITLE
Issues with __cmp__ in Python 3

### ISSUE THREAD

**Issue by ilumsden** [danse-inelastic/pyre#5]
In the unit.py file (/pyre/python/pyre/units/unit.py), on lines 117 and 118, there is the following code:
```
def __cmp__(self, other):
    return cmp(self.value, other.value)
```
The problem is that in Python 3, the `cmp` built-in function has been removed, and the use of created `__cmp__` functions (like the one above) has been depreciated in favor of "rich comparisons" (see http://portingguide.readthedocs.io/en/latest/comparisons.html) for more info.

What do you want me to do about this?

I could try to change the function's contents to reflect the old cmp function, but then, moving forward, we risk Python changing in a way that prevents you from defining a `__cmp__` function.

**Comment by yxqd** [comment]
Could you implement the rich comparing? It seems that you can implement
__eq__, __lt__, and use total_ordering for the rest. We only need to
support python 2.7 and 3
